/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyDataChart: typeof import('./src/components/BodyDataChart.vue')['default']
    BodyDataTable: typeof import('./src/components/BodyDataTable.vue')['default']
    BodyDatatWeeklyWeightChangeChart: typeof import('./src/components/BodyDatatWeeklyWeightChangeChart.vue')['default']
    BodyDataWidgets: typeof import('./src/components/BodyDataWidgets.vue')['default']
    CsvImport: typeof import('./src/components/csv-import/CsvImport.vue')['default']
    CsvImportFileSelection: typeof import('./src/components/csv-import/CsvImportFileSelection.vue')['default']
    CsvImportPreview: typeof import('./src/components/csv-import/CsvImportPreview.vue')['default']
    CsvImportSuccess: typeof import('./src/components/csv-import/CsvImportSuccess.vue')['default']
    DateRangePicker: typeof import('./src/components/infrastructure/DatePicker/DateRangePicker.vue')['default']
    DateRangeSelectionDropdown: typeof import('./src/components/infrastructure/DatePicker/DateRangeSelectionDropdown.vue')['default']
    DateRangeStringified: typeof import('./src/components/infrastructure/DatePicker/DateRangeStringified.vue')['default']
    DateStringified: typeof import('./src/components/infrastructure/DatePicker/DateStringified.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    KeepSlimCard: typeof import('./src/components/KeepSlimCard.vue')['default']
    LocaleSwitch: typeof import('./src/components/LocaleSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleDatePicker: typeof import('./src/components/infrastructure/DatePicker/SingleDatePicker.vue')['default']
    SingleWidget: typeof import('./src/components/widget/SingleWidget.vue')['default']
    SingleWidgetAverageChange: typeof import('./src/components/widget/SingleWidgetAverageChange.vue')['default']
    SingleWidgetInfoIcon: typeof import('./src/components/widget/SingleWidgetInfoIcon.vue')['default']
    SingleWidgetProgressIndicator: typeof import('./src/components/widget/SingleWidgetProgressIndicator.vue')['default']
    SingleWidgetTotalChange: typeof import('./src/components/widget/SingleWidgetTotalChange.vue')['default']
    TextCopy: typeof import('./src/components/infrastructure/TextCopy.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/header/TheHeader.vue')['default']
    TheHeaderTitle: typeof import('./src/components/layout/header/TheHeaderTitle.vue')['default']
    TheHeaderUserMenu: typeof import('./src/components/layout/header/TheHeaderUserMenu.vue')['default']
    TheHeaderUserMenuSettings: typeof import('./src/components/layout/header/TheHeaderUserMenuSettings.vue')['default']
    TheHeaderUserMenuUserIcon: typeof import('./src/components/layout/header/TheHeaderUserMenuUserIcon.vue')['default']
    ThemeDropdown: typeof import('./src/components/ThemeDropdown.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TheNavBar: typeof import('./src/components/layout/TheNavBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
