/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DateRangePicker: typeof import('./src/components/infrastructure/DatePicker/DateRangePicker.vue')['default']
    DateRangeSelectionDropdown: typeof import('./src/components/infrastructure/DatePicker/DateRangeSelectionDropdown.vue')['default']
    DateRangeStringified: typeof import('./src/components/infrastructure/DatePicker/DateRangeStringified.vue')['default']
    DateStringified: typeof import('./src/components/infrastructure/DatePicker/DateStringified.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfoIcon: typeof import('./src/components/InfoIcon.vue')['default']
    KeepSlimCard: typeof import('./src/components/KeepSlimCard.vue')['default']
    LocaleSwitch: typeof import('./src/components/LocaleSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleDatePicker: typeof import('./src/components/infrastructure/DatePicker/SingleDatePicker.vue')['default']
    SingleWidget: typeof import('./src/components/widget/SingleWidget.vue')['default']
    SingleWidgetChangeInDateRangeSelection: typeof import('./src/components/widget/SingleWidgetChangeInDateRangeSelection.vue')['default']
    SingleWidgetInfoIcon: typeof import('./src/components/widget/SingleWidgetInfoIcon.vue')['default']
    SingleWidgetProgressIndicator: typeof import('./src/components/widget/SingleWidgetProgressIndicator.vue')['default']
    SingleWidgetWeeklyAverage: typeof import('./src/components/widget/SingleWidgetWeeklyAverage.vue')['default']
    TextCopy: typeof import('./src/components/infrastructure/TextCopy.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/header/TheHeader.vue')['default']
    TheHeaderTitle: typeof import('./src/components/layout/header/TheHeaderTitle.vue')['default']
    TheHeaderUserMenu: typeof import('./src/components/layout/header/TheHeaderUserMenu.vue')['default']
    TheHeaderUserMenuSettings: typeof import('./src/components/layout/header/TheHeaderUserMenuSettings.vue')['default']
    TheHeaderUserMenuUserIcon: typeof import('./src/components/layout/header/TheHeaderUserMenuUserIcon.vue')['default']
    ThemeDropdown: typeof import('./src/components/ThemeDropdown.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TheNavBar: typeof import('./src/components/layout/TheNavBar.vue')['default']
  }
}
