//----------------------
// <auto-generated>
//     Generated using my buggy toolchain - see: scripts/pre-build-tasks
// </auto-generated>
//----------------------

export const MessageKey = {
	appearance: 'appearance',
	language: 'language',
	profile: 'profile',
	settings: 'settings',
	userSettings: 'userSettings',
	logout: 'logout',
	login: 'login',
	underConstruction: 'underConstruction',
	copied: 'copied',
	entryNotFound: 'entryNotFound',
	oopsSomethingWentWrong: 'oopsSomethingWentWrong',
	unexpectedErrorOccured: 'unexpectedErrorOccured',
	technicalDifficulties: 'technicalDifficulties',
	retry: 'retry',
	environment: 'environment',
	name: 'name',
	version: 'version',
	loadingComplete: 'loadingComplete',
	loadingTook: 'loadingTook',
	goHome: 'goHome',
	pageNotFound: 'pageNotFound',
	settingNotSave: 'settingNotSave',
	close: 'close',
	genericErrorMessage: 'genericErrorMessage',
	german: 'german',
	english: 'english',
	light: 'light',
	auto: 'auto',
	dark: 'dark',
	bodyData: 'bodyData',
};