name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  ci:
    name: Lint, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Run Conventional Commits check
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install packages
        run: npm install

      - name: Lint
        env:
          CI: true
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:unit
